Rummager\Module\Smtp:
  type: entity
  table: smtp
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    check:
      targetEntity: Rummager\Service\Check
      joinColumn:
        name: checkid
        nullable: false
  fields:
    ip:
      type: integer
      unsigned: true
      nullable: false
    port:
      type: integer
      default: 25
      nullable: false
    helo:
      type: text
      nullable: true
      default: null
    helo_code:
      type: integer
      nullable: true
      default: null
    ehlo:
      type: text
      nullable: true
      default: null
    ehlo_code:
      length: 45
      nullable: true
      default: null
    greetings_code:
      type: integer
      nullable: true
      default: null
    greetings_text:
      length: 45
      nullable: true
      default: null
    checktime:
      type: datetime
      nullable: true
      default: null
    tstart:
      type: time
      nullable: true
      default: null
    tcon:
      type: time
      nullable: true
      default: null
    tend:
      type: time
      nullable: true
      default: null
